export const ADD_ITEM_TO_CART = 'ADD_ITEM_TO_CART';
export const REMOVE_ITEM_FROM_CART = 'REMOVE_ITEM_FROM_CART';
export const INCREASE_ITEM_AMOUNT = 'INCREASE_ITEM_AMOUNT';
export const DECREASE_ITEM_AMOUNT = 'DECREASE_ITEM_AMOUNT';
